spring:
  application:
    name: auth-service


server:
  port: 8000
  servlet:
    context-path: /auth

eureka:
  instance:
    # prefer-ip-address:  ${EUREKA_INSTANCE_IP_ADDRESS:${spring.cloud.client.hostname}}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10  # How often the service renews its lease (heartbeat)
    lease-expiration-duration-in-seconds: 60  # How long Eureka waits before marking the service as down
    #non-secure-port: 8000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
