apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: salehinrocky/eureka-service:lb
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: ers-configmap
              key: EUREKA_APPLICATION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service  # it same as hostname in kubernetes cluster
spec:
  selector:
    app: eureka-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761  # port exposed to outside world
      targetPort: 8761 # port inside container
