# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-service-deployment
serviceName: eureka-service
appLabel: eureka-service
appName: eureka-service

replicaCount: 1

image:
  repository: salehinrocky/eureka-service
  tag: lb

containerPort: 8761

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
