# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: auth-service-deployment
serviceName: auth-service
appLabel: auth-service
appName: auth-service

replicaCount: 1

image:
  repository: salehinrocky/auth-service
  tag: lb

containerPort: 8000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

appname_enabled: true
profile_enabled: true
config_enabled: false
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
